language: csharp
solution: "./Lab09/Lab09.sln"
install:
- nuget restore ./Lab09/LAB09.sln
- nuget install NUnit.Runners -Version 3.4.0 -OutputDirectory testrunner -ExcludeVersion
script:
- msbuild /p:Configuration=Release ./Lab09/Lab09.sln
after_script:
- mono ./testrunner/NUnit.ConsoleRunner/tools/nunit3-console.exe Lab09/Lab09/bin/Debug/LAB09.exe
