language: csharp
solution: LAB09.sln
install:
- nuget restore LAB09.sln
- nuget install NUnit.Runners -Version 3.4.0 -OutputDirectory testrunner -ExcludeVersion
script:
- msbuild /p:Configuration=Release LAB09.sln
after_script:
- mono ./testrunner/NUnit.ConsoleRunner/tools/nunit3-console.exe LAB09/bin/Debug/LAB09.exe
